services:
  nethermind-gnosis:
    build:
      context: .
      dockerfile: x64.Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres-gnosis
    networks:
      - circles-gnosis
    ports:
      - 30303:30303/tcp # p2p
      - 30303:30303/udp # p2p
      - 8545:8545
    expose:
      - 8551 # engine api
    volumes:
      - .state/nethermind-gnosis:/data
      - .state/jwtsecret-gnosis/jwt.hex:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      --config=gnosis
      --datadir=/data
      --log=INFO
      --Sync.SnapSync=false
      --JsonRpc.Enabled=true
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=8545
      --JsonRpc.EnabledModules=[Web3,Eth,Subscribe,Net,Circles]
      --JsonRpc.JwtSecretFile=/jwt.hex
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --Network.DiscoveryPort=30303
      --HealthChecks.Enabled=false
    env_file:
      - .env
    environment:
      - V1_HUB_ADDRESS=0x29b9a7fBb8995b2423a71cC17cf9810798F6C543
      - V2_HUB_ADDRESS=0xc12C1E50ABB450d6205Ea2C3Fa861b3B834d13e8
      - V2_NAME_REGISTRY_ADDRESS=0xA27566fD89162cC3D40Cb59c87AAaA49B85F3474
      - V2_STANDARD_TREASURY_ADDRESS=0x08F90aB73A515308f03A718257ff9887ED330C6e
      - V2_ERC20_LIFT_ADDRESS=0x5F99a795dD2743C36D63511f0D4bc667e6d3cDB5
      - POSTGRES_CONNECTION_STRING=Server=postgres-gnosis;Port=5432;Database=postgres;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - START_BLOCK=12000000

  postgres-gnosis:
    image: postgres:16
    command: -c 'max_connections=100'
    restart: unless-stopped
    networks:
      - circles-gnosis
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./.state/postgres-gnosis:/var/lib/postgresql/data

  consensus-gnosis:
    container_name: consensus-gnosis
    image: sigp/lighthouse:v5.3.0-amd64-modern
    restart: always
    networks:
      - circles-gnosis
    ports:
      - 9000:9000/tcp # p2p
      - 9000:9000/udp # p2p
      - 5054:5054/tcp # metrics
    expose:
      - 4000 # http
    volumes:
      - .state/consensus-gnosis/data:/data
      - .state/jwtsecret-gnosis/jwt.hex:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      lighthouse
      beacon_node
      --network=gnosis
      --disable-upnp
      --datadir=/data
      --port=9000
      --http
      --http-address=0.0.0.0
      --http-port=4000
      --execution-endpoint=http://nethermind-gnosis:8551
      --execution-jwt=/jwt.hex
      --checkpoint-sync-url=https://checkpoint.gnosis.gateway.fm/

networks:
  circles-gnosis:
    name: circles-gnosis
